### ISSUE TITLE
tokenizations_controller.rb

### ISSUE THREAD

**Issue by Arawan7** [eonum/medcodeassist#6]
When first saving five tokens to the database and then calling create on tokenizations_controller with the same input as the tokens are called, there should be five entries in the response.body right?
The tokenizations_controller_spec test fails.
If you remove the entry "Lucien" or rename it to "LucienM", everything works as expected.

Note: We had to put an 's' after 'tokenization' in routes.rb to make it work.

**Comment by asittampalam** [comment]
Is this still open?

**Comment by Arawan7** [comment]
Yes it is still open. I think this is clearly a problem on the api side. The commit when I added the failing test is `a13bec23fec8e82034bcbbf145e1e7cd80391d1e` on development branch. It also fails on the latest commit on branch development.

**Comment by asittampalam** [comment]
Sorry, I completely forgot this one.
 I suppose it is because of:

arun@arun-eonum:~/workspace/medcodeassist$ rails console
Loading development environment (Rails 4.2.4)
irb: warn: can't alias context from irb_context.
irb(main):001:0>     stemmer = Lingua::Stemmer.new language: 'de'
=> #<Lingua::Stemmer:0x00000005eddd98 @language="de", @encoding=#<Encoding:UTF-8>>
irb(main):002:0> stemmer.stem "Lucien"
=> "Luci"

So it's not really a problem. You should change your test accordingly.
