### ISSUE TITLE
HTTP POST with httparty

### ISSUE THREAD

**Issue by Arawan7** [eonum/medcodeassist#7]
We struggle with httparty to send a post request to the api and get back the response.

When checking out the branch httparty, then starting the rails server, finally visiting localhost:3000 and clicking on the "Analyse" button, the server log in the console "freezes" at line 15 (see file server_log). Some time later the server is accessible again but there was a `Completed 500 Internal Server Error in 60172ms (Views: 127.5ms)`

We did/tried many things:
- Testing the HTTParty.post method on an other API (`HTTParty.post("http://rubygems.org/api/v1/gems/httparty/owners",
    :query => { :email => "alan+thinkvitamin@carsonified.com" })` succeeded, so the gem works)
- Sending a POST request to the rails server through "Open HttpRequester" addon for firefox; `http://localhost:3000/api/v1/tokenizations?text=Mirko` returned a token that we stored before, so the API is working.
- Because the gem as well as the project's API seem to work, I captured both, the Open HttpRequester and the HTTParty.post, queries with wireshark and compared the headers. Both headers are the same now but still only the Open HttpRequester query works. (see files PluginPOST.pcapng & RailsPOST.pcapng and filter for http)
- We tried faraday as an alternative gem for httparty but there's the same problem

To mention: the method that does the HTTParty.post gets called if you click on the "Analyse" button on the website. This will send the content of the text field with a POST to the controller.

Could you help us please, we're running out of ideas..
Maybe it has something to do with rails?

Files in here: [HTTP POST.zip](https://github.com/eonum/medcodeassist/files/207139/HTTP.POST.zip)

PS:
- make sure mongod is running (`mongod --dbpath [...]/medcodeassist/db --rest`) before you start the rails server.
- then run the tokenizations_controller_spec once to seed your db with the five tokens specified in this test.

**Comment by MBristle** [comment]
As far as I understand the problem, it might be that the controller calls on his own thread, so ruby waits until the first call is finished to hand over to the second and the first call waits for the response of the second call, what ends up in an endless loop... that would explain the timeout error and why it's easily possible to access external APIs, as well as calling the API from outside. Furthermore, the problem seems to appear with whatever gem we use. 
From this Point of view, it seems to me as it would be the easiest way to communicate with the API right from the Javascript (as if it would be our own controller) without making a call to a new controller. 

If this is all right, we could implement the communication with the API like this (at least for this iteration)...

**Comment by asittampalam** [comment]
I'd suggest splitting up the project in an API part and a frontend part (you can use https://github.com/eonum/medcodeassist-frontend for the frontend part) so you aren't restricted in your design because of technical reasons. But apart from that you can decide if you want to access the API on the client side or the server side (or a combination of both).

**Comment by Arawan7** [comment]
We'd like to continue working on https://github.com/eonum/medcodeassist but as solution we could have a running version on our virtual server, provided by university, where we can send post requests.
The question then: is it ok to put the demo data on the server which is only accessible within the VPN of university?

**Comment by tschimbr** [comment]
You just have to rename your repository in .git/config [remote origin] and then push all code to medcodeassist-frontend and remove the API part. It's not that you'd have to start from scratch. Actually it's a fork. Though github does not directly allow to fork one's own repositories. As soon as you have done this we'll remove everything in medcodeassist except the API part.
Regarding the data: It's OK to put the demo on a server accessible within UniBe for a test deployment.
